/**
 * Central type definitions for LexSnap.
 * Per project rules, all shared types live in this file.
 */

/** Learning status of a word (abceed-style buckets). */
export type WordStatus = 'unstudied' | 'known' | 'review'

/** A vocabulary notebook owned by a user. */
export interface Notebook {
  id: string
  user_id: string
  name: string
  created_at: string
}

/** Notebook augmented with word-count breakdowns, used on the home screen. */
export interface NotebookSummary extends Notebook {
  known: number
  review: number
  unstudied: number
}

/** A single vocabulary card stored in the `words` table. */
export interface Word {
  id: string
  notebook_id: string
  word: string
  meanings: string[]
  part_of_speech: string
  example: string
  example_ja: string
  /** IPA phonetic notation, e.g. /prəˌnʌnsiˈeɪʃən/ */
  pronunciation: string
  /** Katakana approximation, e.g. プロナンシエイション */
  pronunciation_kana: string
  definition_en: string
  nuance: string
  status: WordStatus
  created_at: string
}

/** Example sentence length preference (see instructions section 4). */
export type ExampleLength = 'short' | 'medium' | 'long'

/** Card display fields toggled in Settings (see instructions section 5). */
export interface CardFields {
  meaning: boolean
  part_of_speech: boolean
  example: boolean
  example_ja: boolean
  pronunciation: boolean
  /** Katakana reading — display-only toggle, always generated by the Edge Function. */
  pronunciation_kana: boolean
  definition_en: boolean
  nuance: boolean
  example_length: ExampleLength
}

/** Per-user settings persisted to the `user_settings` table. */
export interface UserSettings {
  user_id: string
  card_fields: CardFields
}

/** Request payload sent to the `generate-word` Edge Function. */
export interface GenerateWordRequest {
  word: string
  fields: string[]
}

/** JSON returned by the `generate-word` Edge Function (from Gemini). */
export interface GeneratedWord {
  word: string
  meanings: string[]
  /** English label: noun / verb / adjective … */
  part_of_speech: string
  example: string
  example_ja: string
  /** IPA notation, e.g. /vɜːrb/ */
  pronunciation: string
  /** Katakana approximation, e.g. ヴァーブ */
  pronunciation_kana: string
  definition_en: string
  nuance: string
}

/** Default card fields (see instructions section 5). */
export const DEFAULT_CARD_FIELDS: CardFields = {
  meaning: true,
  part_of_speech: true,
  example: true,
  example_ja: true,
  pronunciation: true,
  pronunciation_kana: false,
  definition_en: false,
  nuance: false,
  example_length: 'medium',
}
